### ISSUE TITLE
4.0?

### ISSUE THREAD

**Issue by avindra** [davglass/zipcodes#16]
Is this project following semver?

I'm trying to determine what are the breaking changes are, if any, in the 4.x release.

Thanks for any advice!

**Comment by davglass** [comment]
Yes, I chose to do a 4.x release based on a newer zip code database being included in #15. This way the data didn't change out from under the users without them manually upgrading.

**Comment by avindra** [comment]
Thanks, that makes sense. It seems like something that all users should upgrade to. Will test.
