### ISSUE TITLE
How accurate are the lat/lng coordinates?

### ISSUE THREAD

**Issue by atsepkov** [davglass/zipcodes#9]
I noticed that latitude and longitude coordinates for the zip codes are limited to 2 decimal places. According to Wikipedia (https://en.wikipedia.org/wiki/Decimal_degrees), that's an error of +/- 1.1 km. That sounds like something that could easily put you in a neighboring zip code instead of the intended one, unless the coordinates are hand-picked to be exactly in the center of the zip code, and given the number of entries in the table that doesn't sound feasible to do for each one.

**Comment by davglass** [comment]
I pull the data from another location, I don't have control over their data, I'm just using it :)
